### ISSUE TITLE
Could not find SAML element in HTML response

### ISSUE THREAD

**Issue by autarchprinceps** [moritzheiber/crowbar#5] opened 2020-12-07 12:56 UTC
```
Authentication successful!
Could not find SAML element in HTML response
```

I always get this, when trying to use crowbar. It also only asked me for my password, never one of my MFA options.

**Comment by moritzheiber** [comment] 2020-12-08 15:50
Hey, thank you for using crowbar. Could you give me some more details about the profile you're connecting with? e.g. are you using Okta or Jumpcloud, which factors do you have configured etc

**Comment by JosephKiranBabu** [comment] 2021-01-30 08:40
I have the same issue when using Okta. I was trying to get a temporary STS token for my user using SAML auth. 

Did a `cargo install crowbar` on Debian testing (after installing libssl-dev and libdbus-1-dev).

```
$ crowbar --version                     
crowbar 0.3.7

$ crowbar profiles add profilename -u username -p okta --url https://myorg.okta.com
Profile profilename added successfully!

$ AWS_PROFILE=profilename aws s3 ls
Password for username at myorg.okta.com: [hidden]
Please select the factor to use:
Enter MFA code: 123456
Authentication successful!
Could not find SAML element in HTML response

Error when retrieving credentials from custom-process: 

$ crowbar exec profilename -- aws s3 ls                                                  
Please select the factor to use:
Enter MFA code: 123456
Authentication successful!
Could not find SAML element in HTML response
```

~/.aws/config looks like this

```
[profile profilename]
credential_process=sh -c 'crowbar creds profilename -p 2> /dev/tty'
```

**Comment by moritzheiber** [comment] 2021-02-01 07:59
@autarchprinceps I've done some debugging with @JosephKiranBabu, and can you verify for me that you are actually using the "full" URL for your profile? The process is described here:

![image](https://user-images.githubusercontent.com/616813/106429843-4eb9a680-646b-11eb-9eec-bf768014e003.png)

(and excerpt from the [README](https://github.com/moritzheiber/crowbar/#adding-a-profile))

The URL should like something like `https://myorg.okta.com/home/amazon_aws/1234567djdjak/123?fromHome=true`

**Comment by moritzheiber** [comment] 2021-10-31 12:39
I'm going to close this issue for the time being as I would wager you've either moved on, resolved the issue in the meantime or cannot reproduce it anymore. Should it persist, please don't refrain from opening another issue. Thanks :heart:

**Closed by moritzheiber** 2021-10-31 12:39 UTC
